var os=require("os");
console.log(os.tmpdir())
//console.log(os.homedir())
console.log(os.endianness())
console.log(os.hostname())
console.log(os.type())
console.log(os.platform())
console.log(os.arch())
console.log(os.release())
console.log(os.uptime())
console.log(os.loadavg())
console.log(os.totalmem())
//consolo.log(os.freemem())
console.log(os.cpus().length)
console.log(os.networkInterfaces())
console.log(os.EOL)